name: moyoung
on:
  push:
    branches:
      - FE_dev
env:
  VITE_BASE_API: ${{ secrets.VITE_BASE_API }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: yarn install
        working-directory: ./src

      - name: Generate build
        run: yarn run build
        working-directory: ./src

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://moyoung-toy-project \
            --delete
        working-directory: ./dist
