name: CI/CD hdev_client to AWS S3

on:
  push:
    branches:
      - FE_dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      // more step...
